Input scene: 	D:/Duan_OneDrive/OneDrive/Documents/cv/assignments_Duan/MeshroomCache/TexturingCL/56aba5c12500457f7ddcc2abaae3bc817037d20d\textures
Input mesh: 	D:/Duan_OneDrive/OneDrive/Documents/cv/assignments_Duan/MeshroomCache/TexturingCL/56aba5c12500457f7ddcc2abaae3bc817037d20d\mesh.ply
Output prefix: 	D:/Duan_OneDrive/OneDrive/Documents/cv/assignments_Duan/MeshroomCache/TexturingCL/56aba5c12500457f7ddcc2abaae3bc817037d20d/texturedMesh
Datacost file: 	
Labeling file: 	
Data term: 	gmi
Smoothness term: 	potts
Outlier removal method: 	none
Tone mapping: 	none
Apply global seam leveling: 	True
Apply local seam leveling: 	True
