Input scene: 	D:/Duan_OneDrive/OneDrive/Documents/cv/assignments_Duan/MeshroomCache/TexturingCL/39e95b72d32755bcd818a500c6286b1087999030\textures
Input mesh: 	D:/Duan_OneDrive/OneDrive/Documents/cv/assignments_Duan/MeshroomCache/TexturingCL/39e95b72d32755bcd818a500c6286b1087999030\mesh.ply
Output prefix: 	D:/Duan_OneDrive/OneDrive/Documents/cv/assignments_Duan/MeshroomCache/TexturingCL/39e95b72d32755bcd818a500c6286b1087999030/texturedMesh
Datacost file: 	
Labeling file: 	
Data term: 	gmi
Smoothness term: 	potts
Outlier removal method: 	none
Tone mapping: 	none
Apply global seam leveling: 	True
Apply local seam leveling: 	True
